### ISSUE TITLE
File naming convention

### ISSUE THREAD

**Issue by SeraphicRav** [bersling/typescript-mongo-express-node-seed#2]
Hi !

Thank you for your work !

I just noticed that there where no real naming convention for the files, sometimes it starts with a capitalized letter, sometimes not. To be consistent with Angular 2, I think the use of snake case would be better (https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-02)

Best regards

**Comment by bersling** [comment]
Thanks for the hint, I too noticed that. I changed now everything to dash case, for example "user-router.ts". When using angular-cli it also generates files in this manner so it's now consistent with that!
